### ISSUE TITLE
URI not updated

### ISSUE THREAD

**Issue by sdaav** [starknet-id/starknetid.js#25]
The URI is not updated when I'm going into different dapps like Flex and Nostra. My former PFP is here, while I wanted to get my Starkurabu PFP.

<img width="468" alt="URI" src="https://github.com/starknet-id/starknetid.js/assets/57441909/b6990a20-2e8b-4377-8fe0-75a7a84f42e0">

Tx set PFP: 0x00be89ad352fee43cd209e10dfc5df80bd14428c171da6be96680b852c1ef52e

**Comment by Th0rgal** [comment]
Is this still the case? @sdaav

**Comment by sdaav** [comment]
Yes is it again!

Le jeu. 14 mars 2024 à 17:38, Thomas Marchand ***@***.***> a
écrit :

**Comment by sdaav** [comment]
@Th0rgal Flex sent a message about the difference API returns when using https://api.starknet.id/id_to_data?id=12 in the documentation as example.

![photo1710583195](https://github.com/starknet-id/starknetid.js/assets/57441909/d75bf332-c615-44b9-8bea-f323ab21d809)

![456a0105-759f-4cb9-b909-a71d427f93cb](https://github.com/starknet-id/starknetid.js/assets/57441909/8e425eaf-54a7-4a68-a5a7-9a4829f8010b)

**Comment by fricoben** [comment]
fixed
